export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOG_OUT = 'LOG_OUT';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_RESPONSE = 'SIGNUP_USER_RESPONSE';
export const SIGNUP_USER_FAILED = 'LOGIN_USER_FAILED';

export const UPDATE_USER_NAME_REQUEST = 'UPDATE_USER_NAME_REQUEST';
export const UPDATE_USER_NAME_RESPONSE = 'UPDATE_USER_NAME_RESPONSE';
export const UPDATE_USER_NAME_FAILED = 'UPDATE_USER_NAME_FAILED';

export const UPDATE_USER_EMAIL_REQUEST = 'UPDATE_USER_EMAIL_REQUEST';
export const UPDATE_USER_EMAIL_RESPONSE = 'UPDATE_USER_EMAIL_RESPONSE';
export const UPDATE_USER_EMAIL_FAILED = 'UPDATE_USER_EMAIL_FAILED';

export const UPDATE_USER_MOBILE_REQUEST = 'UPDATE_USER_MOBILE_REQUEST';
export const UPDATE_USER_MOBILE_RESPONSE = 'UPDATE_USER_MOBILE_RESPONSE';
export const UPDATE_USER_MOBILE_FAILED = 'UPDATE_USER_MOBILE_FAILED';

export const UPDATE_USER_ADDRESS_REQUEST = 'UPDATE_USER_ADDRESS_REQUEST';
export const UPDATE_USER_ADDRESS_RESPONSE = 'UPDATE_USER_ADDRESS_RESPONSE';
export const UPDATE_USER_ADDRESS_FAILED = 'UPDATE_USER_ADDRESS_FAILED';

export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST';
export const UPDATE_USER_PASSWORD_RESPONSE = 'UPDATE_USER_PASSWORD_RESPONSE';
export const UPDATE_USER_PASSWORD_FAILED = 'UPDATE_USER_PASSWORD_FAILED';

export const UPDATE_USER_USERNAME_REQUEST = 'UPDATE_USER_USERNAME_REQUEST';
export const UPDATE_USER_USERNAME_RESPONSE = 'UPDATE_USER_USERNAME_RESPONSE';
export const UPDATE_USER_USERNAME_FAILED = 'UPDATE_USER_USERNAME_FAILED';

export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST';
export const REMOVE_USER_RESPONSE = 'REMOVE_USER_RESPONSE';
export const REMOVE_USER_FAILED = 'REMOVE_USER_FAILED';

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_RESPONSE = 'GET_USER_BY_ID_RESPONSE';
export const GET_USER_BY_ID_FAILED = 'GET_USER_BY_ID_FAILED';

export const UPDATE_USER_IMAGE_REQUEST = 'UPDATE_USER_IMAGE_REQUEST';
export const UPDATE_USER_IMAGE_RESPONSE = 'UPDATE_USER_IMAGE_RESPONSE';
export const UPDATE_USER_IMAGE_FAILED = 'UPDATE_USER_IMAGE_FAILED';
