export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_RESPONSE = 'GET_ALL_POSTS_RESPONSE';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';

export const SEARCH_POSTS_REQUEST = 'SEARCH_POSTS_REQUEST';
export const SEARCH_POSTS_RESPONSE = 'SEARCH_POSTS_RESPONSE';
export const SEARCH_POSTS_FAILED = 'SEARCH_POSTS_FAILED';

export const ADD_LIKE_REQUEST = 'ADD_LIKE_REQUEST';
export const ADD_LIKE_RESPONSE = 'ADD_LIKE_RESPONSE';
export const ADD_LIKE_FAILED = 'ADD_LIKE_FAILED';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_RESPONSE = 'ADD_POST_RESPONSE';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';

export const FILTER_POST_REQUEST = 'FILTER_POST_REQUEST';
export const FILTER_POST_RESPONSE = 'FILTER_POST_RESPONSE';
export const FILTER_POST_FAILED = 'FILTER_POST_FAILED';

export const BLOCK_OR_REPORT_POST_REQUEST = 'BLOCK_OR_REPORT_POST_REQUEST';
export const BLOCK_OR_REPORT_POST_RESPONSE = 'BLOCK_OR_REPORT_POST_RESPONSE';
export const BLOCK_OR_REPORT_POST_FAILED = 'BLOCK_OR_REPORT_POST_FAILED';

export const ADD_COMMENT_TO_POST_REQUEST = 'ADD_COMMENT_TO_POST_REQUEST';
export const ADD_COMMENT_TO_POST_RESPONSE = 'ADD_COMMENT_TO_POST_RESPONSE';
export const ADD_COMMENT_TO_POST_FAILED = 'ADD_COMMENT_TO_POST_FAILED';
