export const GET_ALL_HASHTAGS_REQUEST = 'GET_ALL_HASHTAGS_REQUEST';
export const GET_ALL_HASHTAGS_RESPONSE = 'GET_ALL_HASHTAGS_RESPONSE';
export const GET_ALL_HASHTAGS_FAILED = 'GET_ALL_HASHTAGS_FAILED';
