export const SHOW_ERROR_SNACKBAR = 'SHOW_ERROR_SNACKBAR';
export const HIDE_ERROR_SNACKBAR = 'HIDE_ERROR_SNACKBAR';

export const SHOW_SUCCESS_SNACKBAR = 'SHOW_SUCCESS_SNACKBAR';
export const HIDE_SUCCESS_SNACKBAR = 'HIDE_SUCCESS_SNACKBAR';

export const SHOW_LOADING_SNACKBAR = 'SHOW_LOADING_SNACKBAR';
export const HIDE_LOADING_SNACKBAR = 'HIDE_LOADING_SNACKBAR';
